Javítottam a hibát, ami miatt nem tudtunk teszteket futtatni és ezt a hibajelzést kaptuk:     Caused by: java.lang.NoClassDefFoundError: Failed to link hu/tigra/jee/model/Car (Module \"deployment.test.war:main\" from Service Module Loader): hu/tigra/jee/model/EqualsById"}}
Az EqualsById-t kellett berakni így mindkét tesztben:
                .addClasses(Car.class, CarRegistration.class, Member.class, EqualsById.class, MemberRegistration.class, Resources.class)